export enum EstadosGeneralesKeyEnum {
    LISTAPRECIO = 'LISTAPRECIO',
    PROMOCIONES = 'PROMOCIONES',
    SOLICITUDCOMPRAS = 'SOLICITUDCOMPRAS',
    COTIZACION = 'COTIZACION',
    DEVOLUCION = 'DEVOLUCION',
    ORDENFABRICACION = 'ORDENFABRICACION',
    PRODUCCION = 'PRODUCCION',
    PEDIDO = 'PEDIDO',
    ESTADOSERP = 'ESTADOSERP',
    TRANSFERENCIA='inventario_transferencia_despacho',
    INVENTARIOSOLICITUDDEVOLUCION='INVENTARIOSOLICITUDDEVOLUCION',
    INVENTARIOCAMBIO='INVENTARIOCAMBIO'

}
