export enum EstadosGeneralesKeyEnum {
    LISTAPRECIO = 'LISTAPRECIO',
    PROMOCIONES = 'PROMOCIONES',
    SOLICITUDCOMPRAS = 'SOLICITUDCOMPRAS',
    COTIZACION = 'COTIZACION',
    DEVOLUCION = 'DEVOLUCION',
    ORDENFABRICACION = 'ORDENFABRICACION'
}
