import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [

  {
    path: '/home',
    title: 'Inicio',
    label: '',
    icon: 'mdi mdi-home',
    class: '',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: [],
  },

  // ******************************************************
  {
    path: '/',
    title: 'CRM',
    label: '',
    icon: 'mdi mdi-account-multiple',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: [],
  },

  {
    path: '/',
    title: 'Ventas',
    label: '',
    icon: 'mdi mdi-chart-areaspline',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["ventas"],
    submenu: [
      {
        path: '/ventas/notacredito',
        label: '',
        labelClass: '',
        title: 'Nota Crédito',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_notacredito"],
      },
      {
        path: '/ventas/cotizacion',
        label: '',
        labelClass: '',
        title: 'Cotizaciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_cotizacion"],
      },
      {
        path: '/ventas/ofertas-consulta-factura',
        label: '',
        labelClass: '',
        title: 'Consulta de ofertas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["ventas_ofertas_consulta_factura"],
      },
      {
        path: '',
        title: 'Reportes de Ventas',
        icon: 'mdi mdi-chart-areaspline',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["ventas_reportes"],
        submenu: [
          {
            path: '/ventas/reportes-de-ventas/reporte-ofertas-otorgadas',
            label: '',
            labelClass: '',
            title: 'Ofertas Otorgadas',
            icon: '',
            class: '',
            extralink: false,
            submenu: [],
            permisos: ["ventas_reportes_ofertas_otorgadas"],
          },

          {
            path: '/ventas/reporteprontopago',
            label: '',
            labelClass: '',
            title: 'Pronto Pago',
            icon: '',
            class: '',
            extralink: false,
            submenu: [],
            permisos: ["ventas_reporte_prontopago"]
          },


        ]
      },
    ],
  },
  {
    path: '/',
    title: 'Compras',
    label: '',
    icon: 'mdi mdi-basket',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["compras"],
    submenu: [
      {
        path: '/compras/solicitud-compras',
        label: '',
        labelClass: '',
        title: 'Solicitud de compras',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["compras_solicitud_compra"],
      },
      {
        path: '/compras/orden-compras',
        label: '',
        labelClass: '',
        title: 'Orden de compras',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["compras_orden_compra"],
      },
      // {
      //   path: '/compras/solicitud-compras-autorizacion',
      //   label: '',
      //   labelClass: '',
      //   title: 'Auth. Solicitud de compras',
      //   icon: '',
      //   class: '',
      //   extralink: false,
      //   submenu: [],
      //   permisos: ["compras_solicitud_compra"],
      // },
    ],
  },

  {
    path: '/',
    title: 'Finanzas',
    label: '',
    icon: 'mdi mdi-chart-bar',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: [],
  },
  {
    path: '/',
    title: 'Recursos Humanos',
    label: '',
    icon: 'mdi mdi-account-box',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: [],
  },
  {
    path: '',
    title: 'Inventario',
    label: '',
    icon: 'mdi mdi-package-variant-closed',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [
      {
        path: '/inventario/devoluciones',
        title: 'Devoluciones',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['inventario_devoluciones'],
      },
      // {
      //   path: '/inventario/autorizaciondevoluciones',
      //   title: 'Autorizacion Devoluciones',
      //   label: '',
      //   icon: '',
      //   class: '',
      //   labelClass: '',
      //   extralink: false,
      //   submenu: [],
      //   permisos: ['inventario_autorizacion_devoluciones'],
      // },
    ],
    permisos: ['inventario'],
  },

  {
    path: '/',
    title: 'Produccion',
    label: '',
    icon: 'mdi mdi-archive',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["produccion"],
    submenu: [
      {
        path: '/produccion/pesaje',
        label: '',
        labelClass: '',
        title: 'Sistema de Pesajes',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["produccion_pesaje"],
      },
    ],
  },
  {
    path: '/',
    title: 'Servicios',
    label: '',
    icon: 'mdi mdi-view-module',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    submenu: [],
    permisos: [],
  },


  // ******************************************************




  {
    path: '#',
    title: 'Turno',
    label: '',
    icon: 'mdi mdi-home',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["turnos"],
    submenu: [
      {
        path: '/turno/servicios',
        label: '',
        labelClass: '',
        title: 'Servicios',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["turnos_pantalla"],
      },
      {
        path: '/turno/listado',
        label: '',
        labelClass: '',
        title: 'Listado',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["turnos_listado"],
      },
      {
        path: '/turno/entregas',
        label: '',
        labelClass: '',
        title: 'Entregas',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["turnos_entregas"]
      },
    ]
  },

  {
    path: '',
    title: 'Servicios',
    icon: 'mdi mdi-bullseye',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["servicios"],
    submenu: [
      {
        path: '/servicios/citas',
        label: '',
        labelClass: '',
        title: 'Citas',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_citas"],
      },
      {
        path: '/servicios/recepcion-llamado',
        label: '',
        labelClass: '',
        title: 'Recepción',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_recepcion_llamado"],
      },
      {
        path: '/servicios/ordenes',
        label: '',
        labelClass: '',
        title: 'Mis ordenes de servicio',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_ordenes_de_servicio"],
      },
      {
        path: '/servicios/ordeness',
        label: '',
        labelClass: '',
        title: 'Ordenes de servicio',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_ordenes_de_servicio_general"],
      },
      {
        path: '/servicios/multipuntos',
        label: '',
        labelClass: '',
        title: 'Multipuntos Taller',
        icon: 'mdi mdi-calendar',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["servicios_multipuntos"],
      },

    ]
  },
  {
    path: '',
    title: 'Herramientas',
    icon: 'mdi  mdi-wrench',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["herramientas"],
    submenu: [
      {
        path: '/herramientas/minutas',
        label: '',
        labelClass: '',
        title: 'Minutas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["herramientas_minutas"],
      },
      {
        path: '/herramientas/oasisFord',
        label: '',
        labelClass: '',
        title: 'Oasis Ford',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["herramientas_oasis_ford"],
      },


    ]
  },


  {
    path: '',
    title: 'Mantenimientos',
    icon: 'mdi mdi-table',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["mantenimientos"],

    submenu: [
      {
        path: '/mantenimientos/articulo',
        label: '',
        labelClass: '',
        title: 'Artículos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_articulo"],
      },
      {
        path: '/mantenimientos/articulo-categoria',
        label: '',
        labelClass: '',
        title: 'Artículos Categorias',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_articulo_categoria"],
      },
      {
        path: '/mantenimientos/actividadEconomica',
        label: '',
        labelClass: '',
        title: 'Actividad Económica',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_actividad_economica"],
      },
      {
        path: '/mantenimientos/almacen',
        label: '',
        labelClass: '',
        title: 'Almacenes',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_almacen"],
      },
      // {
      //   path: '/mantenimientos/autorizacionprecios',
      //   label: '',
      //   labelClass: '',
      //   title: 'Autorización de precios',
      //   icon: '',
      //   class: '',
      //   extralink: false,
      //   submenu: [],
      //   permisos: ["mantenimientos_autorizacion_precios"],
      // },
      {
        path: '/mantenimientos/moneda',
        label: '',
        labelClass: '',
        title: 'Moneda',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_moneda"],
      },
      {
        path: '/mantenimientos/listaprecios',
        label: '',
        labelClass: '',
        title: 'Lista de precios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_listas_precios"],
      },

      {
        path: '/mantenimientos/cargamasiva',
        label: '',
        labelClass: '',
        title: 'Carga Masiva',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_carga_masiva"],
      },
      {
        path: '/mantenimientos/promocion',
        label: '',
        labelClass: '',
        title: 'Promociones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_promocion"],
      },
      {
        path: '/mantenimientos/descuentos',
        label: '',
        labelClass: '',
        title: 'Descuento',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_descuento"],
      },
      {
        path: '/mantenimientos/departamento',
        label: '',
        labelClass: '',
        title: 'Departamentos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_departamento"],
      },
      {
        path: '/mantenimientos/ruta',
        label: '',
        labelClass: '',
        title: 'Rutas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_ruta"],
      },
      {
        path: '/mantenimientos/nivelautorizacion',
        label: '',
        labelClass: '',
        title: 'Nivel Autorizacion',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_nivel_autorizacion"],
      },
      {

        path: '/mantenimientos/nivelautorizacionmodulo',
        label: '',
        labelClass: '',
        title: 'Nivel Autorizacion M.',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_nivel_autorizacion_modulo"],
      },
      {
        path: '/mantenimientos/estadosgenerales',
        label: '',
        labelClass: '',
        title: 'Estados Generales',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_estado_general"],
      },
      {
        path: '/mantenimientos/sapconnection',
        label: '',
        labelClass: '',
        title: 'SAP Conexiones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_sap_conexion"],
      },
      {
        path: '/mantenimientos/roles',
        label: '',
        labelClass: '',
        title: 'Roles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_rol"],
      },

      {
        path: '/mantenimientos/permisos',
        label: '',
        labelClass: '',
        title: 'Permisos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_permiso"],
      },
      {
        path: '/mantenimientos/proveedor',
        label: '',
        labelClass: '',
        title: 'Proveedores',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_proveedor"],
      },
      {
        path: '/mantenimientos/enrrollvendedorentregasupervisor',
        label: '',
        labelClass: '',
        title: 'Comisiones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: [""],
      },

















      {
        path: '/mantenimientos/accesorio',
        label: '',
        labelClass: '',
        title: 'Accesorios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_accesorios"],
      },


      {
        path: '/mantenimientos/cita-categoria',
        label: '',
        labelClass: '',
        title: 'Cita Categorias',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cita_categoria"],
      },
      {
        path: '/mantenimientos/comite',
        label: '',
        labelClass: '',
        title: 'Comites',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_comite"],
      },
      {
        path: '/mantenimientos/combustible',
        label: '',
        labelClass: '',
        title: 'Combustibles',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_combustible"],
      },
      {
        path: '/mantenimientos/compania',
        label: '',
        labelClass: '',
        title: 'Compañías',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_compania"],
      },
      {
        path: '/mantenimientos/cliente',
        label: '',
        labelClass: '',
        title: 'Clientes',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cliente"],
      },
      {
        path: '/mantenimientos/dealer',
        label: '',
        labelClass: '',
        title: 'Dealers',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_dealer"],
      },

      {
        path: '/mantenimientos/marca',
        label: '',
        labelClass: '',
        title: 'Marcas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_marca"],
      },
      {
        path: '/mantenimientos/modelo',
        label: '',
        labelClass: '',
        title: 'Modelos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_modelo"],
      },
      {
        path: '/mantenimientos/recall',
        label: '',
        labelClass: '',
        title: 'Recall',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_recall"],
      },
      {
        path: '/mantenimientos/oferta',
        label: '',
        labelClass: '',
        title: 'Oferta',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_oferta"],
      },
      {
        path: '/mantenimientos/receptor-posicion',
        label: '',
        labelClass: '',
        title: 'Receptores Posiciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_receptor_posicion"],
      },
      {
        path: '/mantenimientos/sintoma',
        label: '',
        labelClass: '',
        title: 'Síntomas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cita_sintomas"],
      },
      {
        path: '/mantenimientos/sintoma-categoria',
        label: '',
        labelClass: '',
        title: 'Síntoma Categorias',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_cita_sintoma_categoria"],
      },
      {
        path: '/mantenimientos/sucursal',
        label: '',
        labelClass: '',
        title: 'Sucursales',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_sucursal"],
      },
      {
        path: '/mantenimientos/tag',
        label: '',
        labelClass: '',
        title: 'Tags',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_tag"],
      },
      {
        path: '/mantenimientos/usuario',
        label: '',
        labelClass: '',
        title: 'Usuarios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_usuario"],
      },
      {
        path: '/mantenimientos/usuario-almacen-enrroll',
        label: '',
        labelClass: '',
        title: 'Usuarios Almacen Enrroll',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_usuario_almacen_enrroll"],
      },
      {
        path: '/mantenimientos/vehiculocondicion',
        label: '',
        labelClass: '',
        title: 'Vehículo Condiciones',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_vehiculo_condicion"],
      },
      {
        path: '/mantenimientos/vehiculotipo',
        label: '',
        labelClass: '',
        title: 'Vehículo Tipos',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_vehiculo_tipo"],
      },
      {
        path: '/mantenimientos/tomainventarioruta',
        label: '',
        labelClass: '',
        title: 'Asignacion de rutas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["mantenimientos_asignaciones_rutas"],
      },


    ]
  },
  {
    path: '/',
    title: 'Autorización',
    label: '',
    icon: 'mdi mdi-checkbox-marked-circle',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["autorizacion"],
    submenu: [
      {
        path: '/mantenimientos/autorizacionprecios',
        label: '',
        labelClass: '',
        title: 'Lista de precios',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["autorizacion_lista_precios"],
      },
      {
        path: '/compras/solicitud-compras-autorizacion',
        label: '',
        labelClass: '',
        title: 'Solicitud de compras',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["autorizacion_solicitud_compras"],
      },
      {
        path: '/inventario/autorizaciondevoluciones',
        title: 'Devoluciones',
        label: '',
        icon: '',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: ['autorizacion_devoluciones'],
      },
    ],
  },


  {
    path: '/',
    title: 'Reportes',
    label: '',
    icon: 'mdi mdi-file-chart',
    class: 'has-arrow',
    labelClass: '',
    extralink: false,
    permisos: ["reportes"],
    submenu: [
      {
        path: '/',
        label: '',
        labelClass: '',
        title: 'Inventario',
        icon: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["reportes_inventario"],
        submenu: [
          {
            path: '/reportes/inventario/existencia',
            label: '',
            labelClass: '',
            title: 'Existencia',
            icon: '',
            class: '',
            extralink: false,
            permisos: ["reportes_inventario_existencia"],
            submenu: [
            ],
          },
        ],
      },

    ],
  },

  {
    path: '',
    title: 'Configuraciones',
    icon: 'mdi  mdi-settings',
    labelClass: '',
    label: '',
    class: 'has-arrow',
    extralink: false,
    permisos: ["configuraciones"],
    submenu: [

      {
        path: '/configuraciones/admin-web-panel-sincronizacion',
        label: '',
        labelClass: '',
        title: 'Admin Sincronización',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_admin_panel_sincronizacion"],
      },

      {
        path: '/configuraciones/sap-panel-sincronizacion',
        label: '',
        labelClass: '',
        title: 'SAP Sincronización',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_sap_panel_sincronizacion"],
      },


















      {
        path: '/configuraciones/horario-citas',
        label: '',
        labelClass: '',
        title: 'Horario Citas',
        icon: '',
        class: '',
        extralink: false,
        submenu: [],
        permisos: ["configuraciones_horario_cita"],
      },


    ]
  },




];
