import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [

    {
        path: '/home',
        title: 'Inicio',
        label: '',
        icon: 'mdi mdi-home',
        class: '',
        labelClass: '',
        extralink: false,
        submenu: [],
        permisos: [],
    }, {
        path: '#',
        title: 'Turno',
        label: '',
        icon: 'mdi mdi-home',
        class: 'has-arrow',
        labelClass: '',
        extralink: false,
        permisos: ["turnos"],
        submenu: [
            {
                path: '/turno/servicios',
                label: '',
                labelClass: '',
                title: 'Servicios',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["turnos_pantalla"],
            },
            {
                path: '/turno/listado',
                label: '',
                labelClass: '',
                title: 'Listado',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["turnos_listado"],
            },
            {
                path: '/turno/entregas',
                label: '',
                labelClass: '',
                title: 'Entregas',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["turnos_entregas"]
            },
        ]
    },

    {
        path: '',
        title: 'Servicios',
        icon: 'mdi mdi-bullseye',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["servicios"],
        submenu: [
            {
                path: '/servicios/citas',
                label: '',
                labelClass: '',
                title: 'Citas',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["servicios_citas"],
            },
            {
                path: '/servicios/recepcion-llamado',
                label: '',
                labelClass: '',
                title: 'Recepción',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["servicios_recepcion_llamado"],
            },
            {
                path: '/servicios/ordenes',
                label: '',
                labelClass: '',
                title: 'Mis ordenes de servicio',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["servicios_ordenes_de_servicio"],
            },
            {
                path: '/servicios/ordeness',
                label: '',
                labelClass: '',
                title: 'Ordenes de servicio',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["servicios_ordenes_de_servicio_general"],
            },
            {
                path: '/servicios/multipuntos',
                label: '',
                labelClass: '',
                title: 'Multipuntos Taller',
                icon: 'mdi mdi-calendar',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["servicios_multipuntos"],
            },

        ]
    },
    {
        path: '',
        title: 'Herramientas',
        icon: 'mdi  mdi-wrench',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["herramientas"],
        submenu: [
            {
                path: '/herramientas/minutas',
                label: '',
                labelClass: '',
                title: 'Minutas',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["herramientas_minutas"],
            },
            {
                path: '/herramientas/oasisFord',
                label: '',
                labelClass: '',
                title: 'Oasis Ford',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["herramientas_oasis_ford"],
            },


        ]
    },
    {
        path: '',
        title: 'Mantenimientos',
        icon: 'mdi mdi-table',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["mantenimientos"],

        submenu: [

            {
                path: '/mantenimientos/listaprecios',
                label: '',
                labelClass: '',
                title: 'Lista de precios',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_listas_precios"],
            },
            {
                path: '/mantenimientos/promocion',
                label: '',
                labelClass: '',
                title: 'Promociones',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_promocion"],
            },
            {
                path: '/mantenimientos/descuentos',
                label: '',
                labelClass: '',
                title: 'Descuento',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_listas_precios"],
            },
            {
                path: '/mantenimientos/ruta',
                label: '',
                labelClass: '',
                title: 'Rutas',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_listas_precios"],
            },
            {
                path: '/mantenimientos/nivelautorizacion',
                label: '',
                labelClass: '',
                title: 'Nivel Autorizacion',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_listas_precios"],
            },
            {

                path: '/mantenimientos/nivelautorizacionmodulo',
                label: '',
                labelClass: '',
                title: 'Nivel Autorizacion M.',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_listas_precios"],
            },
            {
                path: '/mantenimientos/estadosgenerales',
                label: '',
                labelClass: '',
                title: 'Estados Generales',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_listas_precios"],
            },
















            {
                path: '/mantenimientos/accesorio',
                label: '',
                labelClass: '',
                title: 'Accesorios',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_accesorios"],
            },
            {
                path: '/mantenimientos/almacen',
                label: '',
                labelClass: '',
                title: 'Almacenes',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_almacen"],
            },
            {
                path: '/mantenimientos/articulo',
                label: '',
                labelClass: '',
                title: 'Artículos',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_articulo"],
            },
            {
                path: '/mantenimientos/cita-categoria',
                label: '',
                labelClass: '',
                title: 'Cita Categorias',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_cita_categoria"],
            },
            {
                path: '/mantenimientos/comite',
                label: '',
                labelClass: '',
                title: 'Comites',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_comite"],
            },
            {
                path: '/mantenimientos/combustible',
                label: '',
                labelClass: '',
                title: 'Combustibles',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_combustible"],
            },
            {
                path: '/mantenimientos/compania',
                label: '',
                labelClass: '',
                title: 'Compañías',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_compania"],
            },
            {
                path: '/mantenimientos/cliente',
                label: '',
                labelClass: '',
                title: 'Clientes',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_cliente"],
            },
            {
                path: '/mantenimientos/dealer',
                label: '',
                labelClass: '',
                title: 'Dealers',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_dealer"],
            },
            {
                path: '/mantenimientos/marca',
                label: '',
                labelClass: '',
                title: 'Marcas',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_marca"],
            },
            {
                path: '/mantenimientos/modelo',
                label: '',
                labelClass: '',
                title: 'Modelos',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_modelo"],
            },
            {
                path: '/mantenimientos/recall',
                label: '',
                labelClass: '',
                title: 'Recall',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_recall"],
            },
            {
                path: '/mantenimientos/oferta',
                label: '',
                labelClass: '',
                title: 'Oferta',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_oferta"],
            },
            {
                path: '/mantenimientos/receptor-posicion',
                label: '',
                labelClass: '',
                title: 'Receptores Posiciones',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_receptor_posicion"],
            },
            {
                path: '/mantenimientos/sintoma',
                label: '',
                labelClass: '',
                title: 'Síntomas',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_cita_sintomas"],
            },
            {
                path: '/mantenimientos/sintoma-categoria',
                label: '',
                labelClass: '',
                title: 'Síntoma Categorias',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_cita_sintoma_categoria"],
            },
            {
                path: '/mantenimientos/sucursal',
                label: '',
                labelClass: '',
                title: 'Sucursales',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_sucursal"],
            },
            {
                path: '/mantenimientos/tag',
                label: '',
                labelClass: '',
                title: 'Tags',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_tag"],
            },
            {
                path: '/mantenimientos/usuario',
                label: '',
                labelClass: '',
                title: 'Usuarios',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_usuario"],
            },
            {
                path: '/mantenimientos/vehiculocondicion',
                label: '',
                labelClass: '',
                title: 'Vehículo Condiciones',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_vehiculo_condicion"],
            },
            {
                path: '/mantenimientos/vehiculotipo',
                label: '',
                labelClass: '',
                title: 'Vehículo Tipos',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["mantenimientos_vehiculo_tipo"],
            },


        ]
    },
    {
        path: '',
        title: 'Ventas',
        icon: 'mdi mdi-chart-areaspline',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["ventas"],
        submenu: [
            {
                path: '/ventas/ofertas-consulta-factura',
                label: '',
                labelClass: '',
                title: 'Consulta de ofertas',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["ventas_ofertas_consulta_factura"],
            },
            {
                path: '',
                title: 'Reportes de Ventas',
                icon: 'mdi mdi-chart-areaspline',
                labelClass: '',
                label: '',
                class: 'has-arrow',
                extralink: false,
                permisos: ["ventas_reportes"],
                submenu: [
                    {
                        path: '/ventas/reportes-de-ventas/reporte-ofertas-otorgadas',
                        label: '',
                        labelClass: '',
                        title: 'Ofertas Otorgadas',
                        icon: '',
                        class: '',
                        extralink: false,
                        submenu: [],
                        permisos: ["ventas_reportes_ofertas_otorgadas"],
                    },


                ]
            },


        ]
    },
    {
        path: '',
        title: 'Configuraciones',
        icon: 'mdi  mdi-settings',
        labelClass: '',
        label: '',
        class: 'has-arrow',
        extralink: false,
        permisos: ["configuraciones"],
        submenu: [
            {
                path: '/configuraciones/horario-citas',
                label: '',
                labelClass: '',
                title: 'Horario Citas',
                icon: '',
                class: '',
                extralink: false,
                submenu: [],
                permisos: ["configuraciones_horario_cita"],
            },


        ]
    },
];
