export enum OrdenFabricacionEstadoEnum {
  PLANIFICADA = 1,
  PENDIENTECONSUMO = 2,
  PROCESANDOCONSUMO = 3,
  PENDIENTETERMINALREPORT = 4,
  PENDIENTECERRAR = 5,
  PENDIENTECERRARSUPERVISORPRODUCCION = 6,
  PENDIENTECERRARGERENTEPRODUCCION = 7,
  PENDIENTECERRARGERENTEPLANTA = 8,
  PENDIENTECERRARADMINISTRACION = 9,
  CERRADA = 10


}
